README.md
Fix https://github.com/geocoder-php/Geocoder/issues/404
=> Add the api key parameter to the google maps provider doc

src/Geocoder/Provider/Chain.php
Need to change the locale dynamically in PHP for after use it with the CacheProvider of GeocoderBundle
=> Allow locale change with chain

composer.json, tests/.cached_responses/d1c35cb39da7fe59b8d2472945443bd0879b8701, tests/Geocoder/Tests/CachedResponseAdapter.php, tests/Geocoder/Tests/Provider/AbstractProviderTest.php
=> [Http] Update egeloen/http-adapter library

src/Geocoder/Model/AdminLevel.php, src/Geocoder/Model/Country.php
=> add __toString() methods in AdminLevel and Country

src/Geocoder/Provider/GeoIP2.php, tests/Geocoder/Tests/Provider/GeoIP2Test.php
=> Fix postal code for GeoIP2 provider

src/Geocoder/Provider/FreeGeoIp.php, tests/.cached_responses/1ec836744699c92949abd980774e110560bc27b3, tests/.cached_responses/3117e4255511124c8c1a097f85f1cad5ae01437f, tests/.cached_responses/6481992b59646c5a15768a664165f44ce0dcbfad, tests/.cached_responses/eb03260dc4bdaaaad3132f9f46171c6d69ae7ff7, tests/Geocoder/Tests/Provider/FreeGeoIpTest.php
=> Return ISO 3166-2 region codes for the US and the rest of the world.

src/Geocoder/Geocoder.php
=> Add throws to geocode/reverse methods of Geocoder interface.

composer.json
We should be more specific with the PHP version. We are not testing for PHP6, PHP8 and PHP9 but our composer file said that we support it. =)
=> Update PHP version syntax

README.md, docs/cookbook/cache.md, docs/cookbook/http-client.md
Im not sure if we want this in the readme since it it out of scope. But is (IMHO) a really common use case and it would be nice for our users not having to figure this out themselves.
=> Adding cookbook

index.markdown
=> Fix link in Geocoder documentation

src/Geocoder/Location.php
=> Removed "Position" and replaced it with "Location"

README.md, src/Geocoder/Dumper/GeoArray.php, tests/Geocoder/Tests/Dumper/GeoArrayTest.php
=> Add geo array dumper

src/Geocoder/Location.php, src/Geocoder/Model/Address.php
=> More explicit documentation with return types

src/Geocoder/Provider/MaxMindBinary.php, tests/Geocoder/Tests/Provider/MaxMindBinaryTest.php
=> Added support for postal code

src/Provider/FreeGeoIp.php, src/Provider/GeoIP2.php, src/Provider/GeoIPs.php, src/Provider/GeoPlugin.php, src/Provider/Geoip.php, src/Provider/HostIp.php, src/Provider/IpAddressGeocoder.php, src/Provider/IpInfoDb.php, src/Provider/MaxMind.php, src/Provider/MaxMindBinary.php
=> Added IpAddressGeocoder interface

src/Provider/GeoIP2.php, tests/Provider/GeoIP2Test.php
=> Remove fixEnconding from GeoIP2

.gitattributes
This is needed for the multi-repo approach
=> Do not remove tests from the composer package

CONTRIBUTING.md
=> Update PSR links in CONTRIBUTING.md

.travis.yml, src/Provider/GoogleMaps/GoogleMaps.php
=> Remove locale from GoogleBusiness

composer.json, src/Provider/GoogleMaps/LICENSE, src/Provider/GoogleMaps/Readme.md, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_56a86eba9a0b3b14e39bc8c0b13a5ebb4a017803, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php, src/Provider/GoogleMaps/phpunit.xml.dist
Added license file, fixed typos and updated to the latest version of the integration tests.
=> Updated tests and added meta files

src/Common/Provider/AbstractHttpProvider.php, src/Provider/ArcGISOnline/ArcGISOnline.php, src/Provider/BingMaps/BingMaps.php, src/Provider/FreeGeoIp/FreeGeoIp.php, src/Provider/GeoIPs/GeoIPs.php, src/Provider/GeoPlugin/GeoPlugin.php, src/Provider/Geonames/Geonames.php, src/Provider/HostIp/HostIp.php, src/Provider/HostIp/Tests/HostIpTest.php, src/Provider/IpInfoDb/IpInfoDb.php, src/Provider/MapQuest/MapQuest.php, src/Provider/Mapzen/Mapzen.php, src/Provider/MaxMind/MaxMind.php, src/Provider/MaxMind/Tests/MaxMindTest.php, src/Provider/Nominatim/Nominatim.php, src/Provider/Nominatim/Tests/NominatimTest.php, src/Provider/OpenCage/OpenCage.php, src/Provider/TomTom/TomTom.php, src/Provider/Yandex/Tests/YandexTest.php, src/Provider/Yandex/Yandex.php
Use the `AbstractHttpProvider::getUrlContents` introduced in #617 for all providers
=> Use AbstractHttpProvider::getUrlContents

src/Common/Model/Address.php
This will completely remove the need from LocationFactory.
The factory method will be used in our tests.
Im not sure we do need a factory class at all. Please review.
=> Added factory method to Address.

src/Provider/Yandex/Model/YandexAddress.php, src/Provider/Yandex/Tests/YandexTest.php, src/Provider/Yandex/Yandex.php
=> Extend result from Yandex

src/Provider/GoogleMaps/GoogleMaps.php
=> Allow to query for result type and location type

CHANGELOG.md, src/Common/Collection.php, src/Common/Geocoder.php, src/Common/GeocoderTrait.php, src/Common/Location.php, src/Common/Model/Address.php, src/Common/Model/AddressCollection.php, src/Common/Model/AdminLevel.php, src/Common/Model/AdminLevelCollection.php, src/Common/Model/Bounds.php, src/Common/Model/Coordinates.php, src/Common/Model/Country.php, src/Common/ProviderAggregator.php, src/Common/StatefulGeocoder.php, src/Common/Tests/TimedGeocoderTest.php, src/Common/TimedGeocoder.php
This adds **some** type hints
Related to #638
=> Added PHP7 type hints

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php
Just added support for 'formatted_address' for GoogleMaps.
=> adding support for formatted_address for GoogleMaps

src/Provider/BingMaps/BingMaps.php
Ping @unkind. I would be happy for a quick review.
=> [Bing Maps] Use LocationBuilder

src/Common/GeocoderTrait.php, src/Common/Provider/Provider.php, src/Common/ProviderAggregator.php, src/Common/StatefulGeocoder.php, src/Common/Tests/ProviderAggregatorTest.php, src/Common/TimedGeocoder.php, src/Provider/ArcGISOnline/ArcGISOnline.php, src/Provider/BingMaps/BingMaps.php, src/Provider/Chain/Chain.php, src/Provider/Chain/Tests/ChainTest.php, src/Provider/FreeGeoIp/FreeGeoIp.php, src/Provider/GeoIP2/GeoIP2.php, src/Provider/GeoIP2/GeoIP2Adapter.php, src/Provider/GeoIPs/GeoIPs.php, src/Provider/GeoPlugin/GeoPlugin.php, src/Provider/Geoip/Geoip.php, src/Provider/Geonames/Geonames.php, src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/HostIp/HostIp.php, src/Provider/IpInfoDb/IpInfoDb.php, src/Provider/MapQuest/MapQuest.php, src/Provider/Mapzen/Mapzen.php, src/Provider/MaxMind/MaxMind.php, src/Provider/MaxMindBinary/MaxMindBinary.php, src/Provider/Nominatim/Nominatim.php, src/Provider/OpenCage/OpenCage.php, src/Provider/TomTom/TomTom.php, src/Provider/Yandex/Model/YandexAddress.php, src/Provider/Yandex/Yandex.php
=> Added type hints

composer.json, src/Provider/Chain/Chain.php, src/Provider/Chain/composer.json
This will also introduce logging
=> [Chain Provider] Removed old/deprecated code

src/Common/Location.php, src/Common/Model/Address.php, src/Common/Model/AddressBuilder.php, src/Common/Model/LocationFactory.php, src/Common/Tests/Dumper/GeoArrayTest.php, src/Common/Tests/Dumper/GeoJsonTest.php, src/Common/Tests/Model/AddressTest.php, src/Provider/BingMaps/BingMaps.php, src/Provider/FreeGeoIp/FreeGeoIp.php, src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/Yandex/Yandex.php
=> Added Address::ProvidedBy

src/Common/Model/AddressBuilder.php, src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_83f7cc6bce3ca2d4e3f1db58f0e2c35cacf1f402, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php
Added support for 'subpremise' for GoogleMaps, related to issue #593
=> Adding support for subpremise for GoogleMaps

src/Provider/IpInfoDb/.travis.yml, src/Provider/IpInfoDb/IpInfoDb.php, src/Provider/IpInfoDb/LICENSE, src/Provider/IpInfoDb/Readme.md, src/Provider/IpInfoDb/Tests/.cached_responses/api.ipinfodb.com_09bacd276ac61e7b1296acd006716b2d698908f7, src/Provider/IpInfoDb/Tests/.cached_responses/api.ipinfodb.com_3e0c2ea897f224b475ec572f0660cf9246a8a898, src/Provider/IpInfoDb/Tests/.cached_responses/api.ipinfodb.com_970635549fd75c3e9c1360045743f9457aa33992, src/Provider/IpInfoDb/Tests/IntegrationTest.php, src/Provider/IpInfoDb/Tests/IpInfoDbTest.php, src/Provider/IpInfoDb/composer.json, src/Provider/IpInfoDb/phpunit.xml.dist
=> Prepare IpInfoDb for new package

src/Provider/GoogleMaps/composer.json
This will create a page at Packagist with all packages that can be used as a provider.
=> Create a virtual package for provider implementation

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_4907e5553f467f40b445d23e5c19609e9f3ac176, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php, tests/.cached_responses/e10f891dd957408d3edf356be6c170808d6b9fb3
=> Google maps provider viewport fallback

src/Provider/Yandex/Yandex.php
=> Add support for toponym for yandex

src/Http/Tests/Provider/AbstractHttpProviderTest.php, src/Provider/FreeGeoIp/Tests/IntegrationTest.php, src/Provider/GeoIP2/Tests/IntegrationTest.php, src/Provider/GeoIPs/Tests/IntegrationTest.php, src/Provider/GeoPlugin/Tests/IntegrationTest.php, src/Provider/Geoip/Tests/IntegrationTest.php, src/Provider/HostIp/Tests/IntegrationTest.php, src/Provider/IpInfoDb/Tests/IntegrationTest.php, src/Provider/MapQuest/Tests/IntegrationTest.php, src/Provider/Mapzen/Tests/IntegrationTest.php, src/Provider/MaxMindBinary/Tests/IntegrationTest.php, src/Provider/OpenCage/Tests/IntegrationTest.php, src/Provider/TomTom/Tests/IntegrationTest.php, src/Provider/Yandex/Tests/IntegrationTest.php
=> Added declare(strict_types=1);

.travis.yml, src/Provider/Geoip/.travis.yml, src/Provider/MaxMindBinary/.travis.yml, src/Provider/MaxMindBinary/Tests/IntegrationTest.php, src/Provider/MaxMindBinary/composer.json
This will make sure we run each provider separately. 
It will also fix #615
=> Improved travis config

src/Common/Dumper/Gpx.php, src/Common/composer.json
=> Removed dependency in igorw

src/Provider/GeoIP2/composer.json, src/Provider/Geoip/composer.json, src/Provider/MaxMindBinary/composer.json
... From providers that do not need it.
=> Remove HTTP dependencies

phpunit.xml.dist, src/Common/Provider/AbstractProvider.php, src/Http/Tests/Provider/AbstractHttpProviderTest.php, src/Provider/ArcGISOnline/ArcGISOnline.php, src/Provider/GeoIP2/GeoIP2.php, src/Provider/GeoIPs/GeoIPs.php, src/Provider/GeoPlugin/GeoPlugin.php, src/Provider/Geoip/Geoip.php, src/Provider/HostIp/HostIp.php, src/Provider/IpInfoDb/IpInfoDb.php, src/Provider/MapQuest/MapQuest.php, src/Provider/Mapzen/Mapzen.php, src/Provider/MaxMind/MaxMind.php, src/Provider/MaxMindBinary/MaxMindBinary.php, src/Provider/OpenCage/OpenCage.php, src/Provider/TomTom/TomTom.php
Most provider did not use this value
=> Added 'providedBy'

CODE_OF_CONDUCT.md, README.md
... to comply with github standards.
=> Moved code of conduct to a separate file

src/Common/Collection.php, src/Common/Geocoder.php, src/Common/GeocoderTrait.php, src/Common/Model/Address.php, src/Common/Model/AddressBuilder.php, src/Common/Model/AddressCollection.php, src/Common/Model/AdminLevel.php, src/Common/Model/AdminLevelCollection.php, src/Common/Model/Country.php, src/Common/ProviderAggregator.php, src/Common/StatefulGeocoder.php, src/Common/TimedGeocoder.php, src/Provider/Chain/Chain.php, src/Provider/MaxMind/Tests/MaxMindTest.php
Every time I review the code I find more missing type hints.
=> Php7 type hints

src/Provider/FreeGeoIp/FreeGeoIp.php
=> Allow you to configure URL for FreeGeoIp

src/Provider/GeoIP2/GeoIP2.php, src/Provider/GeoIP2/Tests/GeoIP2Test.php
I've kept it simple to start with.
=> Geoip2 provider exceptions

src/Common/Query/GeocodeQuery.php, src/Common/Query/ReverseQuery.php, src/Common/Tests/Query/GeocodeQueryTest.php, src/Common/Tests/Query/ReverseQueryTest.php
This is needed for the cache provider (#717) and for Bazinga geocoder logger.
=> Added __toString on queries

composer.json, src/Provider/Cache/.gitattributes, src/Provider/Cache/.gitignore, src/Provider/Cache/.travis.yml, src/Provider/Cache/CHANGELOG.md, src/Provider/Cache/LICENSE, src/Provider/Cache/ProviderCache.php, src/Provider/Cache/Readme.md, src/Provider/Cache/Tests/ProviderCacheTest.php, src/Provider/Cache/composer.json, src/Provider/Cache/phpunit.xml.dist
This provider is caching the result of other providers with simple cache. 
FYI: HTTP providers may use the cache plugin to HTTPlug
=> Adding cache provider

composer.json, src/Common/Assert.php, src/Common/Dumper/AbstractArrayDumper.php, src/Common/Dumper/AbstractDumper.php, src/Common/Dumper/GeoArray.php, src/Common/Dumper/GeoJson.php, src/Common/Dumper/Gpx.php, src/Common/Dumper/Kml.php, src/Common/Dumper/Wkb.php, src/Common/Dumper/Wkt.php, src/Common/Exception/CollectionIsEmpty.php, src/Common/Exception/ExtensionNotLoaded.php, src/Common/Exception/FunctionNotFound.php, src/Common/Exception/InvalidCredentials.php, src/Common/Exception/InvalidServerResponse.php, src/Common/Exception/LogicException.php, src/Common/Exception/OutOfBounds.php, src/Common/Exception/ProviderNotRegistered.php, src/Common/Exception/QuotaExceeded.php, src/Common/Exception/UnsupportedOperation.php, src/Common/Formatter/StringFormatter.php, src/Common/Model/AddressCollection.php, src/Common/ProviderAggregator.php, src/Common/StatefulGeocoder.php, src/Common/Tests/ProviderAggregatorTest.php, src/Common/TimedGeocoder.php, src/Provider/Chain/Tests/ChainTest.php, src/Provider/GeoIP2/GeoIP2Adapter.php, src/Provider/GeoIP2/Tests/GeoIP2AdapterTest.php
Most suggested by scrutinizer.
=> Fixed code smell and clean ups

src/Common/CHANGELOG.md, src/Common/composer.json, src/Provider/Chain/CHANGELOG.md, src/Provider/Chain/composer.json
=> Added change log

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_22d93c8a857ae773b4c8c4c50b016e10871042df, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_9d4613c0165f92fa2b4e894eb2abaf3d08978161, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_c6795bf308428c6c931709e22a5b1a4202b9305c, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_d73e08b0bf4d20e24e7aa5d525900a2f80a6f763, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_e01b3d4c87819ab9786b6191b45320e25001b174, src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_e811ade1b165563520c2f04053be1ceb45fdf7b8, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php
Added address components listed on https://developers.google.com/maps/documentation/geocoding/intro#Types
except  sublocality_level_#
issue #715
=> adding address_components parameters

src/Provider/GoogleMaps/Model/GoogleAddress.php
attempting to improve code quality for the Google Maps provider as stated in issue #737
=> improving docs for GoogleMaps model

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php
=> Cleaned up Google Provider

src/Common/Query/GeocodeQuery.php, src/Common/Query/Query.php, src/Common/Query/ReverseQuery.php
This is useful inte the BazingaBundle to reference both queries. 
It will also be useful in more situations (~~~Big surprise is coming up~~~) (Plugin support)
=> Create interface for Query

src/Common/Query/GeocodeQuery.php
Introduced in #743
Thank you @arubacao
=> Fixed typo

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php
=> Add place_id to GoogleAddress

src/Common/CHANGELOG.md, src/Http/CHANGELOG.md
=> Updated change logs

src/Plugin/composer.json
This PR is to trigger subtree split
=> [Plugin] Updated keywords

src/Plugin/composer.json
=> Updated branch alias on Plugin. 

README.md
=> Updated namespaces

README.md
This will fix #769 
Ping @mikebronner
=> Added note about framework integrations

composer.json, src/Provider/IpInfoDb/IpInfoDb.php
=> Use prefer-stable instead of prefer-dist

src/Common/composer.json, src/Provider/GeoIPs/composer.json, src/Provider/MaxMind/composer.json
I was wrong merging #768 without these changes in composer.json
=> Update requirements to support Country not being null

composer.json, src/Common/composer.json, src/Http/composer.json, src/Plugin/composer.json, src/Provider/ArcGISOnline/composer.json, src/Provider/BingMaps/composer.json, src/Provider/Chain/composer.json, src/Provider/FreeGeoIp/composer.json, src/Provider/GeoIP2/composer.json, src/Provider/GeoIPs/composer.json, src/Provider/GeoPlugin/composer.json, src/Provider/Geoip/composer.json, src/Provider/Geonames/composer.json, src/Provider/GoogleMaps/composer.json, src/Provider/HostIp/composer.json, src/Provider/IpInfoDb/composer.json, src/Provider/LocationIQ/composer.json, src/Provider/MapQuest/composer.json, src/Provider/Mapzen/composer.json, src/Provider/MaxMind/composer.json, src/Provider/MaxMindBinary/composer.json, src/Provider/Nominatim/composer.json, src/Provider/OpenCage/composer.json, src/Provider/PickPoint/composer.json, src/Provider/TomTom/composer.json, src/Provider/Yandex/composer.json
This will fix the build error.
This is a work around. To fix this properly one should remove this file https://github.com/geocoder-php/Geocoder/blob/master/phpunit
=> Fix phpunit version to 6.3.*

src/Provider/Geonames/CHANGELOG.md
=> Added changelog

.idea/php.xml, src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php
You can add an optional parameter to the google maps requests to see the usage on a specific channel.
I added this parameter in this PR.
I also made some code style fixes. I hope its useful for you.
The description is here.
https://developers.google.com/maps/premium/overview?hl=en
=> GoogleMaps: Channel parameter

src/Provider/IpInfo/.gitattributes, src/Provider/IpInfo/.gitignore, src/Provider/IpInfo/.travis.yml, src/Provider/IpInfo/CHANGELOG.md, src/Provider/IpInfo/IpInfo.php, src/Provider/IpInfo/LICENSE, src/Provider/IpInfo/Readme.md, src/Provider/IpInfo/Tests/IntegrationTest.php, src/Provider/IpInfo/Tests/IpInfoTest.php, src/Provider/IpInfo/composer.json, src/Provider/IpInfo/phpunit.xml.dist
This adds support for ipinfo.io
=> Add IpInfo provider

src/Provider/GoogleMaps/CHANGELOG.md
=> Added changelog for GoogleMaps

src/Provider/Cache/ProviderCache.php
=> Make ProviderCache class not final

src/Provider/Here/Readme.md
Merging this PR will also trigger a git subplit.
=> Style fixes

src/Plugin/Plugin/CachePlugin.php, src/Plugin/Tests/Plugin/CachePluginTest.php
See issue https://github.com/geocoder-php/Geocoder/issues/882
With this PR the CachePlugin has an optional argument precision, to store the location in cache with less precision.
PR for the `BazingaGeocoderBundle` to optionally accept the precision argument is coming up after this one is merged and tagged.
=> Add precision argument in CachePlugin

src/Provider/AlgoliaPlaces/composer.json, src/Provider/Here/composer.json, src/Provider/Ipstack/composer.json, src/Provider/Mapbox/composer.json
New packages should not start on version 4.0.
=> Change branch alias to 1.0

src/Provider/OpenCage/Model/OpenCageAddress.php, src/Provider/OpenCage/OpenCage.php, src/Provider/OpenCage/Tests/OpenCageTest.php
https://github.com/geocoder-php/Geocoder/issues/855 have offered use more data.
Added model `OpencageAddress`.
I added only two extra fields: geohash and formatted address.
=> Improve for opencage provider

src/Provider/Yandex/Model/YandexAddress.php, src/Provider/Yandex/Tests/YandexTest.php, src/Provider/Yandex/Yandex.php
Pull request adds "Location kind":
https://tech.yandex.ru/maps/doc/geocoder/desc/reference/kind-docpage/
Actually nothing special here
=> [Yandex] Location "kind" addition

src/Provider/Cache/ProviderCache.php
=> Tiny typo fix

src/Common/CHANGELOG.md
Fixed missing information in common changelog https://github.com/geocoder-php/Geocoder/commit/e6b29095f4ae80493b1d9ffa1cd5d2110d10a54b
=> [Common] Update CHANGELOG.md

src/Provider/OpenCage/OpenCage.php, src/Provider/OpenCage/Tests/OpenCageTest.php
Updated mapping according to official configuration https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml
=> [OpenCage] Update StreetName Locality and SubLocality Mapping

src/Provider/OpenCage/OpenCage.php, src/Provider/OpenCage/Tests/.cached_responses/api.opencagedata.com_658d6162b974c7f12e3b339c31e4b3fd939158f4, src/Provider/OpenCage/Tests/.cached_responses/api.opencagedata.com_8127723d4501e22d1146796e697e16227d2030b8, src/Provider/OpenCage/Tests/.cached_responses/api.opencagedata.com_d65542385285ca7f475e2a337596aecfc93207aa, src/Provider/OpenCage/Tests/.cached_responses/api.opencagedata.com_dbd9478d843c14f73f89986daf57a40250925942, src/Provider/OpenCage/Tests/.cached_responses/api.opencagedata.com_fe2c4178e95d6ffc0a296b72c20d69ee5b7cdd52, src/Provider/OpenCage/Tests/OpenCageTest.php
Added functionality according documentation: https://opencagedata.com/api#ambiguous-results
=> GeocodeQuery with Ambiguous results

src/Provider/MaxMindBinary/MaxMindBinary.php
=> [MaxMindBinary] Issue #946 - Apply utf8_encode only if the field is not null

src/Provider/GoogleMaps/GoogleMaps.php, src/Provider/GoogleMaps/Model/GoogleAddress.php, src/Provider/GoogleMaps/Tests/GoogleMapsTest.php
=> [Google Maps] Implement partial_match 

src/Provider/GraphHopper/composer.json
This PR is party to force push for subtree split
=> [GraphHopper] Update branch alias

src/Provider/Cache/Readme.md
Let me know if there's anything else that I should add 😄 
Closes #762
=> chore: add cache provider docs

src/Provider/Chain/CHANGELOG.md, src/Provider/Chain/Chain.php
Apply PR #880 for **reverse** geocoding
=> [Chain] Improve error message when provider can not *reverse* geocode

src/Provider/GeocodeEarth/composer.json, src/Provider/GoogleMapsPlaces/composer.json
This will also trigger new packages.
=> Updated branch alias

README.md
Few quick updates to the main readme.
- Updated @willdurand's email as requested [here](https://github.com/geocoder-php/geocoder-php.github.io/pull/16)
- Updated badge to use `sheilds.io` (same as other badge) for consistent style + fixing loading issues.
=> chore: update docs email/badge

README.md
Missing "require" in composer command
=> Fix doc README

phpunit.xml.dist, src/Provider/IP2Location/.gitattributes, src/Provider/IP2Location/.gitignore, src/Provider/IP2Location/.travis.yml, src/Provider/IP2Location/CHANGELOG.md, src/Provider/IP2Location/IP2Location.php, src/Provider/IP2Location/LICENSE, src/Provider/IP2Location/Readme.md, src/Provider/IP2Location/Tests/.cached_responses/api.ip2location.com_1117d6d7b84416500ce339acc9c387700fe81440, src/Provider/IP2Location/Tests/.cached_responses/api.ip2location.com_6374ec39c79ddd96577dd81a01c013eb573f5b40, src/Provider/IP2Location/Tests/IP2LocationTest.php, src/Provider/IP2Location/Tests/IntegrationTest.php, src/Provider/IP2Location/composer.json, src/Provider/IP2Location/phpunit.xml.dist, src/Provider/IP2LocationBinary/.gitattributes, src/Provider/IP2LocationBinary/.gitignore, src/Provider/IP2LocationBinary/.travis.yml, src/Provider/IP2LocationBinary/CHANGELOG.md, src/Provider/IP2LocationBinary/IP2LocationBinary.php, src/Provider/IP2LocationBinary/LICENSE, src/Provider/IP2LocationBinary/Readme.md, src/Provider/IP2LocationBinary/Tests/IP2LocationBinaryTest.php, src/Provider/IP2LocationBinary/Tests/IntegrationTest.php, src/Provider/IP2LocationBinary/composer.json, src/Provider/IP2LocationBinary/phpunit.xml.dist
Please consider adding IP2Location into your provider list.
Thanks.
=> Added IP2Location and IP2LocationBinary provider.

README.md, docs/cookbook/rate-limiting.md
This PR adds the example from #1035 into the cookbook as documentation as it seems like useful information :)
=> feat: add rate limiting cookbook documentation

src/Provider/IpInfoDb/IpInfoDb.php, src/Provider/IpInfoDb/Tests/IpInfoDbTest.php
CountryCode is currently missing, while it is among the response data from this provider.
=> CountryCode missing in IpInfoDb provider

composer.json, src/Provider/HostIp/AbstractHostIp.php, src/Provider/HostIp/HostIp.php, src/Provider/HostIp/HostIpXml.php, src/Provider/HostIp/Tests/.cached_responses/api.hostip.info_44e7890e9b0d0400bcc062dcf777052025c91d60, src/Provider/HostIp/Tests/.cached_responses/api.hostip.info_9b95c30c1eebad5d140fc0805f479d0cc76c9bba, src/Provider/HostIp/Tests/.cached_responses/api.hostip.info_c1c1216db2688099687c51037ee22996e8783e54, src/Provider/HostIp/Tests/.cached_responses/api.hostip.info_d5b477a1473f52d2d992ee9be6b193f2ef655a5b, src/Provider/HostIp/Tests/HostIpXmlTest.php, src/Provider/HostIp/composer.json
=> Created HostIpXml all alternative to HostIp

src/Provider/Photon/Photon.php, src/Provider/Photon/Tests/PhotonTest.php
This simple PR adds country codes in the address results for the Photon provider.
Let me know if tests are necessary and I will look into getting those added.
=> [Photon] Add country codes

src/Provider/GoogleMapsPlaces/README.md
Explain how to filters GoogleMap results with components
=> [GoogleMaps] Filters GoogleMaps results with components

src/Plugin/Promise/GeocoderFulfilledPromise.php, src/Plugin/Promise/GeocoderRejectedPromise.php
=> Add return types to Promises

composer.json, src/Provider/GeoIP2/composer.json
https://github.com/maxmind/GeoIP2-php/releases/tag/v3.0.0
=> feat: add support for "geoip2/geoip2" 3

src/Provider/Pelias/CHANGELOG.md, src/Provider/Pelias/Model/PeliasAddress.php
Make potentially nullable properties consistent.
=> [Pelias] Fix potential issue with nullable properties
