geocoder-php/Geocoder

src/Geocoder/Provider/BingMaps.php
tests/Geocoder/Tests/Provider/BingMapsTest.php

By default only country name is retreived from Bing Maps. With an extra request parameter the country code can be retreived as well.

Add countrycode to Bing api calls

---

.travis.yml

* use the faster container-based infrastructure
* remove unneeded `sh` wrapper
* don't specify default `--dev` argument
* run tests against the lowest possible dependency versions too

improve Travis builds

---

README.md

Since its acceptance, the PSR-7 document has been moved from proposed to accepted FIG standards. As a result, all the links that were targeting the proposed document became broken.
This PR fixes this by updating links in the README in order to make them reference the new location of PSR-7.

Update links to PSR-7 spec

---

src/Geocoder/Provider/Yandex.php
tests/Geocoder/Tests/Provider/YandexTest.php

This fix removes the `E_WARNING: Invalid argument supplied for foreach()`

Bugfix, Sometimes $data is null at this point.

---

src/Geocoder/Provider/Geoip.php

The `geoip_region_name_by_code()` and `geoip_time_zone_by_country_and_region()` require both arguments (country and region) should be provided. Code which previously served as a part of this verification has been removed 16.11.2012 (b4c48686) by Christaudo contributor. Now behaviour is wrong becouse of empty `region` in `geoip_record_by_name` very common situation and provide `You need to specify the country and region codes.` error message.
This pull request add this verification back.

Fix emergency message in Geoip provider

---

src/Geocoder/Model/AdminLevelCollection.php

Fix wrong order of sprintf`s params in Geocoder\Model\AdminLevelCollection::checkLevel

Fixes #468

---

src/Geocoder/Provider/FreeGeoIp.php

Add the missing `timezone` field for `FreeGeoIp` provider.

[FreeGeoIp] Add the missing timezone field

---

.travis.yml

This adds a check for PHP7 to the HHVM-Check. Therefore on PHP7 the
PECL-GeoIP-Extension shouldn't be loaded. Instead the
geoip/geoip-package is required on PHP7.
It could also be required for HHVM, but I'm not sure that works...

Fixes Travis-Build

---

src/Geocoder/Provider/OpenCage.php
tests/.cached_responses/8d579eb3ca22f821281bd4f15c3eb1c3fd73fb11
tests/Geocoder/Tests/Provider/OpenCageTest.php

use city, town village or hamlet as locality

[OpenCage] Locality

---

src/Geocoder/Provider/MapQuest.php
tests/Geocoder/Tests/Provider/MapQuestTest.php

The MapQuest API returns a two-letter country-code and no country name. Currently that Country-code is returned as country name when using the MapQuest-Adapter. But it is not returned as CountryCode though.
This PR solves that by adding the CountryCode.
To handle BC returning that 2 letter code as country-name is kept AS IS.

Adds coutry-code to MapQuest-Results

---

.gitattributes

Please ignore your test suite for export, otherwise it will blow the vendor directory due to that large `GeoLiteCity.dat`.

ignore tests for export

---

src/Geocoder/Provider/OpenCage.php
tests/Geocoder/Tests/Provider/OpenCageTest.php

Throw `InvalidCredentials`, `QuotaExceeded` where needed. Tests pass. Thanks for providing this awesome framework!

Handle invalid API key, over quota respones for OpenCage provider

---

src/Geocoder/Geocoder.php

I don't know if version 2.x  is still maintained ... but if it can be help.

fix: use statement for a phpdoc return tag

---

src/Geocoder/Geocoder.php

This is just a minor thing. PHPStorm was complaining about this.

Added full namespace to exceptions

---

tests/Geocoder/Tests/CachedResponseClient.php

Although the cached unit test responses are serialised, the unit test code framework doesn't actually serialise any new responses that are added to the cache directory. This fixes that.

Fix bug where cached unit test responses aren't serialised

---

README.md

The `README` in `master` branch contains information for Geocoder 4.0.

Update links to documentation in README

---

README.md
composer.json

Use phpunit from vendor to prevent issues
don't suggest to rename `phpunit.xml.dist` 
https://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.xml-configuration
If there is no `phpunit.xml` then phpunit will use `phpunit.xml.dist` , so whats the point in renaming it?

Update unittest passage

---

README.md

php-http/message contains the GuzzleMessageFactory needed
for message factory auto discovery to work.

Add php-http/message to README install instructions

---

src/Common/Exception/InvalidServerResponse.php
src/Common/Provider/AbstractHttpProvider.php
src/Provider/GoogleMaps/GoogleMaps.php

This will be a unified way to throw some exceptions
This will reduce the number of checks in each provider.

Create a common function to fetch data form server

---

CHANGELOG.md
src/Provider/ArcGISOnline/ArcGISOnline.php
src/Provider/ArcGISOnline/Tests/ArcGISOnlineTest.php

This will replace #566 and fix #489

ArcGIS provider : street name must use StAddr attribute

---

src/Common/Query/GeocodeQuery.php
src/Common/Query/ReverseQuery.php
src/Provider/Nominatim/Nominatim.php

This will fix #598
This PR will also update `*Query::getData` to be more DX.

Allow to set zoom

---

src/Provider/GoogleMaps/GoogleMaps.php
src/Provider/GoogleMaps/Model/GoogleAddress.php
src/Provider/Yandex/Model/YandexAddress.php
src/Provider/Yandex/Yandex.php

From the discussion at https://github.com/geocoder-php/Geocoder/pull/624
FYI @unkind

Make custom addresses immutable

---

src/Provider/Geoip/.travis.yml
src/Provider/MaxMindBinary/.travis.yml

The providers that need php extension geoip must be tested on trusty

Test on trusty

---

src/Common/Assert.php
src/Common/Exception/LogicException.php
src/Common/Exception/OutOfBoundsException.php
src/Common/Exception/ProviderNotRegistered.php
src/Common/Model/AddressBuilder.php
src/Common/Model/AddressCollection.php
src/Common/Model/AdminLevelCollection.php
src/Common/ProviderAggregator.php
src/Provider/GoogleMaps/GoogleMaps.php

The `\LogicException` in `AddressBuilder` will only be thrown if the provider is doing something strange (ie wrong programming).
How about the `\OutOfBoundsException` in `AddressCollection` and `AdminLevelCollection`. Should we create our own `OutOfBoundsException`?

All exceptions should be ours

---

src/Common/ProviderAggregator.php

Marking classes as `final` does have benefits in certain situations but many sources recommend doing so only when:
* There is an abstraction (interface) that the final class implements
* All of the public API of the final class is part of that interface
The particular thing that broke in my case was that it's not possible to mock `ProviderAggregator` anymore (and I'm testing the thin wrapper I wrote around it) as mocking final classes in `phpunit-mock-objects` (the default mocking library for phpunit) is not possible.
I would be happy (and could open a PR with such change) if we extract an inteface from the `ProviderAggregator` and leave it final.
Addresses #727

Mark ProviderAggregator as NOT final.

---

src/Common/CHANGELOG.md
src/Common/ProviderAggregator.php
src/Common/Tests/ProviderAggregatorTest.php

From https://github.com/geocoder-php/Geocoder/issues/727#issuecomment-312446873
> One potential case for extending (or providing an alternative implementation of such aggregator) is such where you would have a certain logic to automatically select a provider based on your query. For example -> use geoip2 for valid IP address geocode() calls, use google maps for anything else. Given the popularity of the library, I think more options to extend the library are better.
Ping @ddinchev

Added a callable to decide what provider that should be used.

---

src/Common/CHANGELOG.md
src/Common/ProviderAggregator.php
src/Common/Tests/ProviderAggregatorTest.php

Removed GetLimit

---

src/Common/Query/GeocodeQuery.php
src/Common/Query/ReverseQuery.php

Decorators or plugins may want to rewrite the query somehow. This PR allows that.

Add withText and withCoordinates.

---

src/Geocoder/Provider/AbstractProvider.php
tests/Geocoder/Tests/Provider/GeoIP2Test.php

We're using GeoIPs provider with Maxmind binary database and we started getting weird enconding results. We found out that coming from database some strings are already UTF-8.
Running ``utf8_encode()`` on those strings will break the encoding.
This fix will only apply ``utf8_encode()`` if the string is not UTF-8
Tests are green.

Do not convert to UTF-8 if already UTF-8

---

composer.json
src/Plugin/.gitattributes
src/Plugin/.travis.yml
src/Plugin/CHANGELOG.md
src/Plugin/Exception/LoopException.php
src/Plugin/LICENSE
src/Plugin/Plugin.php
src/Plugin/Plugin/BoundsPlugin.php
src/Plugin/Plugin/CachePlugin.php
src/Plugin/Plugin/LimitPlugin.php
src/Plugin/Plugin/LocalePlugin.php
src/Plugin/Plugin/LoggerPlugin.php
src/Plugin/Plugin/QueryDataPlugin.php
src/Plugin/PluginProvider.php
src/Plugin/Promise/GeocoderFulfilledPromise.php
src/Plugin/Promise/GeocoderRejectedPromise.php
src/Plugin/Readme.md
src/Plugin/Tests/Plugin/BoundsPluginTest.php
src/Plugin/Tests/Plugin/CachePluginTest.php
src/Plugin/Tests/Plugin/LimitPluginTest.php
src/Plugin/Tests/Plugin/LocalePluginTest.php
src/Plugin/Tests/Plugin/LoggerPluginTest.php
src/Plugin/Tests/Plugin/QueryDataPluginTest.php
src/Plugin/Tests/PluginProviderTest.php
src/Plugin/composer.json
src/Plugin/phpunit.xml.dist

When creating the BazingaBundle we could either decorate all providers with a CacheProvider, LoggerProvider, ProfilingProvider etc... or we could use a PluginProfiler. This basically rips all nice plugin classes created by php-http and modify them to our needs. 
I put these plugin files in a new package, `geocoder-php/plugin`, because they have a few external dependencies. 
I've added 6 plugins to modify or log the queries. 
FYI @joelwurtz, @sagikazarmark
(Blocked by #741)
```php
$provider = new GoogleMapsProvider();
$pluginProvider = new PluginProvider($provider, [
new LocalePlugin('sv'),
new CachePlugin($cacheService),
new LoggerPlugin($logger),
]);
$query = GeocodeQuery::create('foobar');
$result = $pluginProvider->geocodeQuery($query);
// $result is in Swedish
// $result is cached
// …
```

Adding Plugin support

---

src/Provider/Nominatim/Nominatim.php

On this URL for example: https://nominatim.openstreetmap.org/search?q=Italia&format=xml&addressdetails=1&limit=5
We receive locations without countryCode:
<place place_id="85100707" osm_type="way" osm_id="62194429" place_rank="17" boundingbox="-62.1766268,-62.1725491,-58.51788,-58.5084623" lat="-62.1750648" lon="-58.5135405" display_name="Italia, Antarctica" class="waterway" type="stream" importance="0.435">
<stream>Italia</stream>
<continent>Antarctica</continent>
</place>
In that case, the following error happens: **Type error: strtoupper() expects parameter 1 to be string, null given**.
This PR fixes this by not uppercasing the countrycode if it does not exist.

[Fix] NominatimProvider: do not throw error when countryCode is missing

---

src/Provider/Geonames/Geonames.php

Check if `geonames` key exists before accessing it

Check if geonames key exists

---

src/Provider/Nominatim/Nominatim.php

Hi,
Tiny fix here, coordinates weren't passed in the right order to AddressBuilder::setBound in the Nominatim provider, north and west was inverted, made Bounds attributes inconsistent.

Fixing order of coordinates passed to AddressBuilder::setBound 

---

src/Common/Exception/InvalidServerResponse.php
src/Common/Query/GeocodeQuery.php
src/Common/Query/ReverseQuery.php
src/Provider/FreeGeoIp/FreeGeoIp.php
src/Provider/GoogleMaps/GoogleMaps.php
src/Provider/Mapzen/Mapzen.php
src/Provider/OpenCage/OpenCage.php
src/Provider/Yandex/Model/YandexAddress.php

As reported: https://styleci.io/analyses/qxKNJB in PR: https://github.com/geocoder-php/Geocoder/pull/798

StyleCi fixes

---

src/Provider/GoogleMaps/Model/GoogleAddress.php
src/Provider/Nominatim/Nominatim.php

When using Nominatim provider, the API can return several kinds of responses for "city" for the same kind of query.
For example:
**75004, France**
https://nominatim.openstreetmap.org/search?q=75004,France&format=xml&addressdetails=1&limit=5
<suburb>Quartier Saint-Merri</suburb>
<city_district>4th Arrondissement</city_district>
<city>Paris</city>
<county>Paris</county>
<state>Ile-de-France</state>
<country>France</country>
<postcode>75004</postcode>
=> we receive the city in a "city" field
**98000, Monaco**
https://nominatim.openstreetmap.org/search?q=98000%2C+Monaco&format=xml&addressdetails=1&limit=5
<suburb>La Condamine</suburb>
<town>Monaco</town>
<postcode>98000</postcode>
<country>Monaco</country>
=> we receive the city field in a "town" field
Here is the wiki for Nominatim …

In Nominatim provider, use city, then town, then village, then hamlet

---

src/Provider/GeoPlugin/GeoPlugin.php

If the location of the ip address cannot be determined by GeoPlugin, return an empty AddressCollection instead of dummy data. This is particularly useful when using the Chain provider.

GeoPlugin: Return empty collection if address was not found

---

src/Provider/HostIp/HostIp.php

If the location of the ip address cannot be determined by HostIp, return an empty AddressCollection instead of dummy data. This is particularly useful when using the Chain provider.

HostIp: Return empty collection if address was not found

---

src/Common/StatefulGeocoder.php

After choosing to use bounds or locale with a query, the returned query object must be used.

Use the returned query after setting bounds or locale

---

src/Provider/GoogleMaps/Model/GoogleAddress.php

I would love to keep this, but it is a BC break. :/

Removed return types

---

src/Provider/GoogleMaps/Model/GoogleAddress.php

This return type is a BC break

[Google maps] Removed return types

---

src/Provider/Cache/CHANGELOG.md
src/Provider/Cache/ProviderCache.php

I'd like my cache keys to be namespaced.  The easiest way for me to do so would be to simply override the `getCacheKey` method to work how I want and pass that to the geocoder.  However that's not possible with it being final.
I don't want to reimplement every single method (read: copy and paste).  Therefore I propose marking this class _not_ final so that this method and the `getName` method can be overridden.  I have marked the other methods as final and changed the private properties to protected.

Make ProviderCache not final

---

src/Provider/TomTom/TomTom.php

Instead of bounds like in GoogleMaps, TomTom allows to pass a list of countries to the query to limit the results to specific country. Since the `Query` class already supports adding custom fields through the `setData` and `getData` methods, this feature can easily supported by just adding three lines of code to the `TomTom` provider class.

Add countrySet support for TomTom

---

src/Http/Provider/AbstractHttpProvider.php

As requested in https://github.com/geocoder-php/Geocoder/pull/829. Since `getUrlContents()` takes the url as a string argument, it is not possible to set headers, such as `Accept-Language`, for the request. Therefore I created `getRequest()` to generate the request based on the url string, but without fetching the contents. Then headers can be added to the request, before the request is passed to `getRequestContents()` which fetches the content.

Split getUrlContents

---

src/Provider/FreeGeoIp/FreeGeoIp.php
src/Provider/FreeGeoIp/composer.json

Use `getRequest` and `getParsedResponse` from `AbstractHttpProvider` instead of duplicating code in `FreeGeoIp`. See https://github.com/geocoder-php/Geocoder/pull/864.

Use AbstractHttpProvider in FreeGeoIp

---

src/Provider/Chain/Chain.php

in case a provider can NOT geocode an address / query

Improve error message in case a provider can NOT geocode an address / query

---

src/Common/Model/Bounds.php
src/Provider/Mapbox/CHANGELOG.md
src/Provider/Mapbox/Mapbox.php

When using Bound, the query was malformed in two ways:
- the format was wrong (`|` is not allowed);
- ~~the order was wrong (`minLon,minLat,maxLon,maxLat` was not respected).~~
I also added some documentation to the "Bound" object because it may not be clear to everyone what the min latitude can be when reading compass points.

[Mapbox] Fix Mapbox Query builder when there is Bound

---

src/Provider/GoogleMaps/GoogleMaps.php
src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_52985ec7762d4de3d6f1e0b41b881be875413899
src/Provider/GoogleMaps/Tests/GoogleMapsTest.php

Hi!
First of all, thanks for a great library.
I noticed that [component filtering](https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering) was missing for the Google Maps provider, so i took the liberty of implementing it. Not sure if this can cause any issues with backwards compatibility.

Google Maps component filtering

---

src/Provider/Photon/composer.json

PHP 7.0 is not longer supported. 
This PR will also trigger a push to https://github.com/geocoder-php/photon-provider

[Photon] Require PHP 7.1

---

src/Common/Dumper/GeoJson.php

It implements the method, as expected, but won't satisfy checks for the interface, without this change.

Mark GeoJson dumper as Dumper implementation

---

src/Provider/GoogleMaps/Model/GoogleAddress.php

This should fix the "Administrative level X is defined twice" error (see #793).
@benwrigley @geodeveloper @fritzmg Could one of you test it and confirm ? Thanks

[Google Maps] Fix "Administrative level X is defined twice"

---

src/Provider/GeoIP2/README.md

This PR updates the docs for the geoip2 provider to make then clearer on how to use the database and web service.
I did consider adding a test for the API client, but unfortunately I don't think is possible due to the lack of dependency injection on the `Client` class.
cc @jbelien

chore: update geoip2 documentation

---

.travis.yml

Since PHP 7.3 was released in December last year I think we should switch the CI to test it.
I ran the suite locally and had no errors, but a PR is needed to trigger a CI build.
Also added in a composer cache to speed things up a little bit :)

chore: run tests on php 7.3

---

.travis.yml

This PR adds an extra helper command `GEOIP_EXT_REMOVE` to remove the geoip extension once the test that requires it has run.
This is needed because there are other tests that require it's not installed.
For more info, see #983 
cc @jbelien 
Closes #983

chore: fix ci geoip conflicts

---

src/Provider/FreeGeoIp/FreeGeoIp.php
src/Provider/FreeGeoIp/Readme.md
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_500b2d9369a4fc679d5ceb9a418cf02bf10d013d
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_56adadaf03f9037e7cae3a464b6dc9617f814883
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_66299fd8d42b096fa031b8d1832fc8eb50277552
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_77986275ed32e32047ac76a39223f623f52033bc
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_8aaa58eef1ef2a53923da060d6a9de0db75bf96d
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_8c694912ce2a0ccbf93c7f24111247dbea9916ad
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_9a5acb5700a246cf22916f12ecea2dd2a58c99bb
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_bcc32e827a944478cb862d570202ef3e941ff8ef
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_d1b17a8025172d4e89a00e1386d65cfff66ca0ce
src/Provider/FreeGeoIp/Tests/.cached_responses/freegeoip.net_ec36afcdc6f9803d67dedca58c4421f83ecedda5
src/Provider/FreeGeoIp/Tests/FreeGeoIpTest.php
src/Provider/FreeGeoIp/Tests/IntegrationTest.php

freegeoip.net shut down > 1 year ago, so I think it makes sense to update the provider.
Since it will still work with the open source, self hosted variant i've just updated the constructor default to `null` and throw an exception when trying to geocode without explicit setting of a host.
cc @jbelien

fix: update freegeoip post-shutdown

---

src/Provider/Pelias/CHANGELOG.md
src/Provider/Pelias/LICENSE
src/Provider/Pelias/Pelias.php
src/Provider/Pelias/README.md
src/Provider/Pelias/Tests/IntegrationTest.php
src/Provider/Pelias/Tests/PeliasTest.php
src/Provider/Pelias/composer.json
src/Provider/Pelias/phpunit.xml.dist

Pelias is an open-source geocoder. You can find its [documentation here](https://github.com/pelias/documentation).
Pelias does not provide an API per se but other API (and providers) are based on Pelias and extend this provider.
Geocode Earth will be updated to extend this new provider (see #1005).

New Pelias provider

---

src/Provider/GoogleMaps/GoogleMaps.php
src/Provider/GoogleMaps/Model/GoogleAddress.php
src/Provider/GoogleMaps/Tests/.cached_responses/maps.googleapis.com_db9847acc1c9be42852ac89be82c87e3cecdd7c2
src/Provider/GoogleMaps/Tests/GoogleMapsTest.php

The google maps provider is missing the `postal_code_suffix` field as per issue #1006.
This adds the field + test, and fixes some styling issues.
Closes #1006

fix: add postal_code_suffix to google maps provider

---

src/Provider/AlgoliaPlaces/README.md

Key and app-id were inverted in the code example vs constructor signature in the implementation.
A quote was missing in another line.

Fix code example

---

README.md

Currently the docs are a little bit unclear in regards to how to use different http drivers.
You don't actually need to install `php-http/message`, guzzle installs their own PSR7 implementation.
I added another example command with the curl client, to demonstrate that a PSR7 implementation is required if not using guzzle.
Closes #1021

docs: update install commands

---

src/Common/ProviderAggregator.php
src/Common/Tests/ProviderAggregatorTest.php

Exception tries to implode the providers list, but providers doesn't have `__toString` implementations  and so it fails.
```
PHP Warning:  Uncaught ErrorException: Catchable Fatal Error: Object of class Geocoder\Plugin\PluginProvider could not be converted to string in ~/www/sf/vendor/willdurand/geocoder/Exception/ProviderNotRegistered.php:29
Stack trace:
#0 ~/www/sf/vendor/willdurand/geocoder/ProviderAggregator.php(148): Geocoder\Exception\ProviderNotRegistered::create('address', Array)
#1 ~/www/sf/vendor/willdurand/geocoder-bundle/Command/GeocodeCommand.php(69): Geocoder\ProviderAggregator->using('address')
#2 ~/www/sf/vendor/symfony/console/Command/Command.php(255): Bazinga\GeocoderBundle\Command\GeocodeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), …
```

Fix building ProviderNotRegistered exception message

---

README.md
src/Common/Tests/ProviderAggregatorTest.php
src/Provider/GoogleMaps/GoogleMaps.php
src/Provider/GoogleMaps/Readme.md
src/Provider/GoogleMaps/Tests/GoogleMapsTest.php

Google maps has required an api key for fairly long time, but it's missing from the documentation (which might confuse people copy/pasting).
I've added the api key to the params in the code example
Closes https://github.com/geocoder-php/Geocoder/issues/1028

docs: update google maps code in readme

---

README.md

I was planning in adding in the other ones that were missing, but these two seem to be the only ones with active support :(
I did find this Zend module, but it's using 3x and hasn't been updated in ages.
https://github.com/geocoder-php/GeocoderModule
There's a fork here that's more up to date however:
https://github.com/mb-tec/GeocoderModule
The silex package is even older, on 2.x and not updated in 3y:
https://github.com/geocoder-php/GeocoderServiceProvider
There's also a cakephp library out there, but it's on 3x as well
https://github.com/dereuromark/cakephp-geo
cc @jbelien

docs: update framework section

---

src/Common/Exception/Exception.php

PhpStan warns of an error about this
```
124    PHPDoc tag @throws with type Geocoder\Exception\Exception is not subtype of Throwable
```
And this has no impact as each exception inherits from \Exception

Exception interface should extend Throwable interface

---

src/Provider/GoogleMapsPlaces/Model/OpeningHours.php
src/Provider/GoogleMapsPlaces/Tests/.cached_responses/maps.googleapis.com_5f76dcb4d0da39264119518d4c3251e461456a1a
src/Provider/GoogleMapsPlaces/Tests/GoogleMapsPlacesTest.php

If you perform the following request you will see that the value of "opening_hours" is an empty object and "open_now" is not set.
https://maps.googleapis.com/maps/api/place/textsearch/json?location=51.0572773,13.7763207&rankby=distance&type=transit_station&key=YOUR_API_KEY
```javascript
{
"results": [
{
"id": "b427385cd417b5851b4e23de4225d102ffc2aa43",
"opening_hours": {},
// ...
},
// ...
],
// ...
}
```
This will result in the following error.
```
In OpeningHours.php line 76:
Notice: Undefined property: stdClass::$open_now
```
Therefore, we should check if the property "open_now" exists.

GoogleMapsPlaces: check if value "open_now" in "opening_hours"

---

src/Provider/GoogleMapsPlaces/Model/GooglePlace.php

Sometimes Google Maps does not return a Plus Code.
PoC:
{"query":"[object] (Geocoder\\Query\\GeocodeQuery: GeocodeQuery: {\"text\":\"Port of Ijmuiden, North Holland, Netherlands, Port Ijmuiden Port\",\"bounds\":\"null\",\"locale\":null,\"limit\":5,\"data\":{\"mode\":\"search\",\"fields\":\"formatted_address, geometry, icon, name, place_id, plus_code, types\"}})"} 
The first 2 results have a PlusCode but the rest do not, which generates an exception.

[Google Maps] Added missing nullable return type

---

src/Provider/GoogleMapsPlaces/CHANGELOG.md
src/Provider/GoogleMapsPlaces/GoogleMapsPlaces.php
src/Provider/GoogleMapsPlaces/Model/GooglePlace.php
src/Provider/GoogleMapsPlaces/README.md
src/Provider/GoogleMapsPlaces/Tests/.cached_responses/maps.googleapis.com_054c8db076eec46678b544d1358e3df127997c59
src/Provider/GoogleMapsPlaces/Tests/.cached_responses/maps.googleapis.com_34ca2302705dac87bbf61dc867dedec2689f7f5d
src/Provider/GoogleMapsPlaces/Tests/.cached_responses/maps.googleapis.com_3dbee0e11374dbb94b51394ea5e903b82d810372
src/Provider/GoogleMapsPlaces/Tests/.cached_responses/maps.googleapis.com_54cbb5269e846e48b22b9ad8ad8fe4475ea4d6f9
src/Provider/GoogleMapsPlaces/Tests/GoogleMapsPlacesTest.php

Resolves https://github.com/geocoder-php/Geocoder/issues/1063
The reverse query was using `Search` (requires Type). 
This PR adds support for `Nearby`, which can be used with:
rankby:prominence + radius (=default `Nearby` combination)
rankby:distance + type/keyword/name (distance + type is very similar to the original `Search`)
Note: `Search` returns formatted_address, `Nearby` returns vicinity.

[Google Places] fix + support both reverse modes: Search & Nearby

---

src/Provider/ArcGISOnline/Readme.md

To better clarify the update to the ArcGISOnline Provider I have updated the Readme as follows:
- Explain why there are 2 methods for geocoding
- Provide information about tokens (why/when needed, lifetime, link to instructions for making one)
- Fix some typos
This was prompted by my proposed [update to the Drupal Geocoder module](https://www.drupal.org/project/geocoder/issues/3179963) in support of my previous update to the ArcGISOnline Provider. Since the token has a max lifetime of 14 days, the Drupal code stores the credentials for obtaining a token, and automatically gets a new token when the existing one has expired. However, this generated some confusion due to the `token` method requiring a `token` value while the Drupal UI is requesting values for `client_id` and `client_secret` …

[ArcGISOnline] Updated Readme to clarify token creation/use.

---

src/Provider/GeocodeEarth/README.md

This PR updates the GeocodeEarth provider README:
- add example usage
- provide more clarity on where to get an API key
- link to the official docs
> note: I haven't written any PHP in like 10 years so please let me know if anything can be improved ;)
I'll likely follow up with some updates to the Pelias and Mapzen providers.

[GeocodeEarth] Update README

---

src/Common/Dumper/AbstractArrayDumper.php
src/Common/Model/Address.php
src/Common/Model/AddressBuilder.php
src/Common/Model/AddressCollection.php
src/Common/Model/AdminLevelCollection.php
src/Common/ProviderAggregator.php
src/Common/Query/GeocodeQuery.php
src/Common/StatefulGeocoder.php
src/Http/Provider/AbstractHttpProvider.php
src/Plugin/Plugin/LimitPlugin.php
src/Plugin/Plugin/LocalePlugin.php
src/Provider/Pelias/Pelias.php
src/Provider/TomTom/TomTom.php

The function `empty()` is a very loose comparison (see [manual](https://www.php.net/manual/en/function.empty)), it's recommended to use more strict comparison (also close #1124).
- Replace `empty($string)` for strings by `null !== $string && strlen($string) > 0`
- Replace `empty($array)` for arrays by `null !== $array && count($array) > 0`
---
I left `empty()` for all the `Bounds` check because I don't really see how to replace it by a more strict check but I think it should be updated as well.
@Nyholm What do you consider an "empty bound" ?
---
I left an `empty()` in [`AbstractArrayDumper`](https://github.com/geocoder-php/Geocoder/blob/c02b93a471a4e7043448b518183d449ceefa81b9/src/Common/Dumper/AbstractArrayDumper.php#L29-L31) because I think it makes sense to keep a loose check there. …

Replace empty() by more strict checks

---

src/Plugin/Plugin/LocalePlugin.php

Previous PR #1125 brought an error in the LocalePlugin.
```php
if (empty($query->getLocale())) {
$query = $query->withLocale($this->locale);
}
```
was replaced by 
```php
$locale = $query->getLocale();
if (null !== $locale && '' !== $locale) {
$query = $query->withLocale($this->locale);
}
```
instead of
```php
$locale = $query->getLocale();
if (null === $locale || '' === $locale) {
$query = $query->withLocale($this->locale);
}
```

Fix LocalePlugin

---

src/Provider/Nominatim/Nominatim.php

If arg_separator is not set, the default value comes from arg_separator.output which is not always set to the value we need here, which is '&'. On Ubuntu the default is '&amp;amp;'. There is no need to adhere to any system defaults here because we know exactly in which context the URLs we build are used: for a backend request that is executed soon in the same PHP handler. The same parameters are used in the MapQuest provider.

[Nominatim] Set optional parameters of http_build_query

---

src/Plugin/Tests/Promise/GeocoderFulfilledPromiseTest.php
src/Plugin/Tests/Promise/GeocoderRejectedPromiseTest.php

Ref: https://github.com/geocoder-php/Geocoder/pull/1151#issuecomment-1048874991

Add tests to promises

---

src/Provider/MapTiler/MapTiler.php
src/Provider/MapTiler/Tests/IntegrationTest.php

[MapTiler] Expect a PSR-18 client instead of a PHP-HTTP client

---

README.md

Follow up of #1110 with some leftover links to PHP-HTTP.

Change links in README.md from PHP-HTTP to PSR-18

---

.github/workflows/component.yml
.github/workflows/php.yml
.github/workflows/provider.yml

bump github actions versions to fix deprecations message for Node 12.

chore: add ci tests for php 8.2, bump github actions versions

---

.github/actions/subtree/action.yml
.github/workflows/subtree.yml
src/Provider/GoogleMaps/phpunit.xml.dist

Until now, [Subtree Split service](https://www.subtreesplit.com/) was used to split the main repository to smaller repositories for each component (Common, Http, Plugin) and provider.
There is currently an issue with that service since mid-2022 but I just discovered it now (ping @Nyholm) and I can't seem to figure out what's going on.
Since all of our CI/CD tasks have been migrated to GitHub Actions, I thought about migrating that "Subtree split" to GitHub Actions as well and that's what this PR is about.
This workflow is based on [GitHub documentation](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository) and works like this:
1. Detect if there are changes if component/provider directory
2. If there are changes, extract Git history and …

Make "Subtree Split" using GitHub Actions

---

src/Provider/Cache/ProviderCache.php
src/Provider/Cache/Tests/ProviderCacheTest.php

ProviderCache: Add option to separate cache between providers

---

src/Provider/Here/Here.php

Undefined index: LocationId at /var/www/api/html/releases/20230704155244/vendor/geocoder-php/here-provider/Here.php:258 Not all the location responses from Here maps reverse geocode API include LocationId, e.g. if the LocationType is area.

Fix Reverse Geocode failure - Here maps - Undefined index: LocationId

---

.github/workflows/subtree.yml

This PR https://github.com/geocoder-php/Geocoder/pull/1200 broke our subtree split. I reverse it now to get it working.

Revert subtree action back to checkout v3

---

src/Provider/IP2LocationBinary/IP2LocationBinary.php
src/Provider/IP2LocationBinary/composer.json
src/Provider/MaxMindBinary/MaxMindBinary.php
src/Provider/MaxMindBinary/composer.json

Trying to avoid `utf8_encode` deprecation warning on PHP 8.2+
It will try to do the same using `mbstring` or `iconv`  functions depending on available extension, and eventually fallback to utf8_encode (not to break BC?).
It's a bit of duplicated code - but I didn't think this specific case (used in two providers only) would warrant moving it to parent class.

Utf8 encode

---

src/Provider/Photon/Model/PhotonAddress.php
src/Provider/Photon/Photon.php
src/Provider/Photon/Tests/.cached_responses/photon.komoot.io_1452fda1b72428b0f5de90de04038275fd7f7e7e
src/Provider/Photon/Tests/PhotonTest.php

The idea here is to get the city in the PhotonAddress Model when the object returned by Photon is of type "city".
For example : [https://photon.komoot.io/reverse?lon=13.38890&lat=52.51644&lang=default&limit=1&layer=city&radius=10](https://photon.komoot.io/reverse?lon=13.38890&lat=52.51644&lang=default&limit=1&layer=city&radius=10)
In this example, we don't have the field city returned by Photon because it is the city element itself (so in this case the city/locality name is in the `name` field).
I also added :
- support for `radius` and `layer` query params as documented here [https://github.com/komoot/photon](https://github.com/komoot/photon)
- wrapping `type` in PhotonAddress model

[Photon] Improve locality for city layer & Add layer & radius query params

---

src/Provider/OpenCage/Model/OpenCageAddress.php
src/Provider/OpenCage/OpenCage.php
src/Provider/OpenCage/Tests/OpenCageTest.php

We have a business case where we would need the accuracy/confidence from the providers we are using. This PR adds this for OpenCage.

Return confidence from OpenCage API
